name: SEO Audit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  seo:
    uses: 2YH02/seo-better/.github/workflows/reusable-audit.yml@main
    with:
      urls: >-
        https://www.yonghun.me
        https://www.yonghun.me/posts
        https://www.yonghun.me/projects/1
    secrets:
      token: ${{ secrets.SEO_BETTER_TOKEN }}
    permissions:
      pull-requests: write